name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Running the script file
      run: |
        echo --Running Tests ---
        sh ./AutomationTests/scripts/run.sh
    
    - name: Check if reports folder exists
      run: if [ -d "./reports" ]; then echo "Reports folder exists"; else echo "Reports folder does not exist"; fi

    - name: Check files in root directory
      run: ls

    - name: Publish the reports folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: PublishReports
        path: ./reports

    - name: Publishing LivingDoc report to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports

    - name: Load Allure test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build Allure test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: ./reports/allure-results

    - name: Publishing Allure report to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history