name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Running the script file
      run: |
        echo --Running Tests ---
        sh ./scripts/run.sh
    - name: Publish the report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: SpecflowReport
        path: ./reports
